module.exports = {
  scan: require('./scan'),
  connect: require('./connect'),
  connectAll: require('./connect-all'),
  shutdownAll: require('./shutdown-all'),
  standAloneModeAll: require('./stand-alone-mode-all'),
  chargingIndicationAll: require('./charging-indication-all'),
  stopModeAll: require('./stop-mode-all'),
  standbyModeAll: require('./standby-mode-all'),
  txPowerAll: require('./tx-power-all'),
  colorAll: require('./color-all'),
  fadeAll: require('./fade-all'),
  rainbowAll: require('./rainbow-all'),
  strobeAll: require('./strobe-all'),
  randomColorAll: require('./random-color-all'),
  uploadAll: require('./upload-all'),
  runSequenceAll: require('./run-sequence-all'),
  effectOnEventAll: require('./effect-on-event-all'),
  removeEffectOnEventsAll: require('./remove-effect-on-events-all'),
  rawAll: require('./raw-all')
};